Don't revert Jira status if LP hasn't actually reverted
mclemenceau/lp-to-jira-sync pull request #2
Opened 2023-12-05 19:46 UTC by schopin-pro

There are some cases where the actual work will be done but the LP
status of the bug will not move, as the LP status has specific semantics
tied to a published package in the archive, and in some cases the work
will only be done in a Git repo but will wait for a later bulk upload to
be reflected in any published package.

For example, this frequently happens for systemd and glibc.

In addition, when working on an SRU, the uploaded package can be stuck
for a while in the SRU queue before publication, and can also sometimes
take a while before released into the release pocket.

Allowing a Jira issue to move to Done and stay there while the LP task
is still in one of those states makes working on those tasks much
easier, without having to remember to remove the relevant tag from the
issue.

2023-12-12 23:06 UTC, mclemenceau requested changes
Thanks for the contribution unfortunately, it didn't work with my local testing.
I will need to do better comments in the future to prevent this as some data structure may be somewhat obscure.
Also thanks for the typing changes, I'm too familiar with this so I will look into that further.
Bottom line, this logic could work but we may have to make a call about which task to prioritize among the possible series affected. Ideally we can identify the devel serie and ignore the other status.
It appears we have a function lp_status that isn't being used that could probably be changed to do what we actually want here.

2023-12-13 08:42 UTC, schopin-pro commented on lp_to_jira_sync/lp_to_jira_sync.py
> +    if task.status in (
I pushed a fix that should work, under the assumptions that all tasks in a given `all_task` item are about the relevant package.

2023-12-13 08:43 UTC, schopin-pro commented on lp_to_jira_sync/lp_to_jira_sync.py
> +def process_issues(all_tasks: dict[Bugset, Any], all_issues: dict[Bugset, Issue], config):
Fixed, thanks!

2023-12-13 20:03 UTC, mclemenceau requested changes
Working as expected, lightly tested with actual Jira project. Note that this would require all the subtasks to be in Progress states or it would be moved back to Triaged
Other than that breakpoint() to be removed, I'm happy with it

2023-12-13 20:03 UTC, mclemenceau commented on tests/test_lp_to_jira_sync.py
> +    breakpoint()
Can you remove that breakpoint ?

2023-12-14 09:13 UTC, schopin-pro commented on tests/test_lp_to_jira_sync.py
> +    breakpoint()
Silly me!

2023-12-14 14:50 UTC, merged